# Generated by Django 2.2.18 on 2021-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210203_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
