# Generated by Django 2.2.18 on 2021-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='departamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
