# Generated by Django 2.2.18 on 2021-02-09 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biologia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordenadas_Integradas_Aves_Chinalco_Seca_2018',
            new_name='Coordenadas_Integradas_Aves',
        ),
    ]
