# Generated by Django 2.2.18 on 2021-02-09 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biologia', '0002_auto_20210209_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenadas_Integradas_Aves_2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_vegetacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estacion', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_conteo', models.CharField(blank=True, max_length=255, null=True)),
                ('zona', models.CharField(blank=True, max_length=255, null=True)),
                ('este', models.IntegerField(blank=True, null=True)),
                ('norte', models.IntegerField(blank=True, null=True)),
                ('altitud', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('temperie', models.CharField(blank=True, max_length=255, null=True)),
                ('conservacion_estacion_muestreo', models.CharField(blank=True, max_length=255, null=True)),
                ('impacto_actividad_humana_cercana', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_punto_conteo', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
