# Generated by Django 2.2.18 on 2021-02-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0003_coordenadas_integradas_aves_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenadas_Integradas_Aves',
        ),
    ]
