# Generated by Django 2.2.18 on 2021-02-09 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biologia', '0004_delete_coordenadas_integradas_aves'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coordenadas_Integradas_Aves_2018',
            new_name='Coordenadas_IntegradasAves2018',
        ),
        migrations.RenameField(
            model_name='coordenadas_integradasaves2018',
            old_name='este',
            new_name='este1',
        ),
        migrations.RenameField(
            model_name='coordenadas_integradasaves2018',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='coordenadas_integradasaves2018',
            old_name='norte',
            new_name='norte1',
        ),
    ]
