# Generated by Django 2.2.18 on 2021-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0006_auto_20210209_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_anfibios_reptiles_bd',
            name='codigo_quebrada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bd_anfibios_reptiles_bd',
            name='conducta_reproductva_in_situ',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bd_anfibios_reptiles_bd',
            name='estado_conservacion_habitat',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
