# Generated by Django 2.2.18 on 2021-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0007_auto_20210209_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='tipo_evaluacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Cuantitativo'), (2, 'Cualitativo')], default=1),
        ),
    ]
