# Generated by Django 2.2.18 on 2021-02-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0008_auto_20210210_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='estado_conservacion_habitat',
            field=models.IntegerField(blank=True, choices=[(1, 'Impactado'), (2, 'Regular'), (3, 'Bueno')], default=1),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='periodo_dia',
            field=models.IntegerField(blank=True, choices=[(1, 'Diurno'), (2, 'Tarde'), (3, 'Nocturno')], default=1),
        ),
    ]
