# Generated by Django 2.2.18 on 2021-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0012_auto_20210212_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfuerzo_muestreo_bd_mamiferos',
            name='mamiferos_mayores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='esfuerzo_muestreo_bd_mamiferos',
            name='mamiferos_menores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
