# Generated by Django 2.2.18 on 2021-02-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0013_auto_20210212_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensacion_ambiental_vegetacion_2018',
            old_name='y_norte',
            new_name='y_este',
        ),
    ]
