# Generated by Django 2.2.18 on 2021-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0014_auto_20210212_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='fecha_registro',
            field=models.DateField(blank=True),
        ),
    ]
