# Generated by Django 2.2.18 on 2021-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0015_auto_20210216_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadasintegradasaves2018',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotos_integrado_aves_chinalco_seca_2018',
            name='fecha_toma',
            field=models.DateField(blank=True, null=True),
        ),
    ]
