# Generated by Django 2.2.18 on 2021-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0016_auto_20210216_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='fecha_registro',
            field=models.DateField(blank=True),
        ),
    ]
