# Generated by Django 2.2.18 on 2021-02-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0017_auto_20210216_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
