# Generated by Django 2.2.18 on 2021-02-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0019_auto_20210216_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='fecha_registro',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_bd',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
