# Generated by Django 2.2.18 on 2021-02-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0020_auto_20210217_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfuerzo_muestreo_bd_mamiferos',
            name='unidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
