# Generated by Django 2.2.18 on 2021-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0021_esfuerzo_muestreo_bd_mamiferos_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
