# Generated by Django 2.2.18 on 2021-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0023_auto_20210219_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='DS_O04_2014_MINAGRI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='actividad_humana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='categoria_abundancia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='cites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='codigo_colecta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='codigo_fotos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='colector_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='conducta_reproductiva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='congregatoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='datum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='distancia_punto_conteo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='edad_reproductiva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='especie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='especie_ambiente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='especie_endemica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='estado_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='familia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='fuente_clasificacion_taxonomica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='grupo_triofico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='hora_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='institucion_deposito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='iucn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='longitud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='metodo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='migratoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='numero_total_individuos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='observaciones_etologia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='observaciones_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='orden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='preparacion_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='registro_auditivo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='registro_captura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='registro_casual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='registro_visual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='restringida_bioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='restringida_eba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='temperie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='tipo_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='tipo_locomocion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='tipo_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='zona_endemismo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
