# Generated by Django 2.2.18 on 2021-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0025_auto_20210219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
