# Generated by Django 2.2.18 on 2021-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0026_auto_20210219_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='codigo_fotos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
