# Generated by Django 2.2.18 on 2021-02-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0027_auto_20210223_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='CITES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='DAP_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='DS0432006AG',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='FOTO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='IUCN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='altura_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='cobertura_vegetal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='colector_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='datum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='disciplina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='endemico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='especie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='estado_conservacion_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='familia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='fenologia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='fuente_clasificacion_taxonomica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='habito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='metodo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='numero_individuos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='orden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='proyeccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='subunidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='temporada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='tipo_evaluacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='tipo_ganado_observado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='tipo_uso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='uso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='x_norte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base_datos_vegetacion_2018',
            name='y_norte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='CITES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='DSO342004AG',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='IUCN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='actividad_humana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='altura_registro_distancia_vertical_suelo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='animal_instalaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='conducta_reproductva_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='conducta_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='datum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='distancia_componente_minero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='distancia_perpendicular_unidad_muestreo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='distribucion_especie_endemica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='especie_endemica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='estado_conservacion_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='estado_hallazgo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='estado_reproductivo_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='etologia_comportamiento_individuo_registrado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='grupo_trofico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='habito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='longitud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='longitud_ano_hocico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='longitud_cola_lagartijas_serpientes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='medida_control_impedir_ingreso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='micro_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='micro_habitat_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='nivel_endemismo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='numero_registro_captura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='numero_registro_directo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='numero_registro_indirecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='numero_total_individuos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='observaciones_animales_muertos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='observaciones_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='planta_dominante_microhabitat_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='profundidad_hojarrasca_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='registro_dieta_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='riesgo_contacto_animal_instalaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='temperie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='territorialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='tipo_evaluacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='tipo_habitat_in_situ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='tipo_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='tipo_reproduccion_anfibios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='uso_potencial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_anfibios_reptiles_bd',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='CITES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='DSO042014AG',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='IUCN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='actividad_humana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='adulto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='codigo_colecta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='codigo_fotos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='colector_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='conducta_reproductiva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='conducta_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='crias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='datum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='disciplina_biologica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='distancia_perpendicular_unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='distancia_unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='especie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='especie_endemica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='especie_segun_ambiente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='estado_conservacion_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='estado_hallazgo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='estado_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='estado_reproductivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='familia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='fuente_clasificacion_taxonomica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='grupo_trofico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='infantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='institucion_deposito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='juvenil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_antebrazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_cola',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_oreja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_pata',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_tibia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='longitud_tragus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='metodo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='micro_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='nivel_endemismo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='numero_estaciones_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='numero_registro_directo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='numero_registro_indirecto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='numero_total_individuos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='observaciones_etologia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='observaciones_sobre_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='orden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='periodo_dia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='proyeccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='registro_captura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='registro_dieta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='subunidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tamaño_unidad_muestreo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='temperie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='temporada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_evaluacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_habitat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_locomocion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_preparacion_muestra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='tipo_registro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='uso_potencial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bd_mamiferos_bd_mamiferos',
            name='zona_endemismo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_bd_mamiferos',
            name='actividades',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora_bd_mamiferos',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='FOTO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='altitud_msnm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='altura_materia_organica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='altura_total_muestra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='altura_vegetacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='area_muestra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='colector_registro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='datum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='disciplina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='especie_dominante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='estado_conservacion_habitat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='metodo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='observacion_impacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='profundidad_total_calicata',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='proyeccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='subunidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='tamaño_unidad_muestreo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='temporada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='x_norte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compensacion_ambiental_vegetacion_2018',
            name='y_este',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_reporte_bd_mamiferos',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_reporte_bd_mamiferos',
            name='grupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_reporte_bd_mamiferos',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_reporte_bd_mamiferos',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coordenadas_reporte_bd_mamiferos',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='codigo_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='esfuerzo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='estacion_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='tamaño_unidad_metros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='temporada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='unidad_esfuerzo_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='unidad_muestreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='esfuerzo_muestreo_bd_vegetacion_2018',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja1_bd',
            name='estacion_monitoreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja1_bd',
            name='unidad_vegetacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja3_bd_vegetacion_2018',
            name='CITES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja3_bd_vegetacion_2018',
            name='DS0432006AG',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja3_bd_vegetacion_2018',
            name='IUCN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja3_bd_vegetacion_2018',
            name='endemico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hoja3_bd_vegetacion_2018',
            name='especies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
