# Generated by Django 2.2.18 on 2021-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0028_auto_20210223_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadas_bd',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
